### ISSUE TITLE
com.github.dhaval2404.imagepicker.provider.CropProvider.<init>(CropProvider.kt:45)

### ISSUE THREAD

**Issue by hasansidd** [Dhaval2404/ImagePicker#110]
I am seeing a few of these pop up on my crashlytics. I see the user is using xposed, but don't have much data on what they are doing to cause this. Looks like activity.intent.extras is being force unwrapped, would it be possible to gracefully fail if it is null?

Caused by kotlin.KotlinNullPointerException
       at com.github.dhaval2404.imagepicker.provider.CropProvider.<init>(CropProvider.kt:45)
       at com.github.dhaval2404.imagepicker.ImagePickerActivity.loadBundle(ImagePickerActivity.kt:83)
       at com.github.dhaval2404.imagepicker.ImagePickerActivity.onCreate(ImagePickerActivity.kt:56)
       at android.app.Activity.performCreate(Activity.java:6679)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6119)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)

**Comment by Dhaval2404** [comment]
Duplicate of #122
