### ISSUE TITLE
Caused by java.lang.NumberFormatException: For input string: "/storage/emulated/0/Download/X X/X.jpg"

### ISSUE THREAD

**Issue by bobbyirawan09** [Dhaval2404/ImagePicker#161]
Hi, thank you for this awesome library. But I have an issue. As the title name, the exception happens when try to converting the document ID from the `URI` to type `Long`. Here's the print stack trace of the error.

Caused by java.lang.NumberFormatException: For input string: "/storage/emulated/0/Download/X X/X.jpg"
       at java.lang.Long.parseLong(Long.java:583)
       at java.lang.Long.valueOf(Long.java:808)
       at com.github.dhaval2404.imagepicker.util.FileUriUtils.getPathFromLocalUri(FileUriUtils.java:78)
       at com.github.dhaval2404.imagepicker.util.FileUriUtils.getRealPath(FileUriUtils.java:29)
       at com.github.dhaval2404.imagepicker.provider.GalleryProvider.handleResult(GalleryProvider.java:114)
       at com.github.dhaval2404.imagepicker.provider.GalleryProvider.onActivityResult(GalleryProvider.java:101)
       at com.github.dhaval2404.imagepicker.ImagePickerActivity.onActivityResult(ImagePickerActivity.java:133)
       at android.app.Activity.dispatchActivityResult(Activity.java:7458)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4354)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4403)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6692)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

I think the stack trace quite clear but I can't reproduce this kind of error. It's affecting 3 users for now, but it might be growing. Could you at least tell me what's wrong or how this could be fixed since I can't debug when try to reproduce the issue.

Notes: 
1. I'm using version 1.8 with `inline-activity-result-kotlin` version 1.0.4
2. The X is the name of the file, it's private so I can't tell the exact name, but the format is the same. The X.jpg contains in the folder with name X X, yes there's a space, just to let you know

Hope to hear from you soon, thanks

**Comment by ratheeshcn** [comment]
@bobbyirawan09 Did you find a solution for this ? Im also getting the same issue on Galaxy Note 8

**Comment by Dhaval2404** [comment]
@bobbyirawan09 @ratheeshcn 
Please migrate to v2.0. It no longer uses FileUriUtils hence the issue will be fixed now.
