### ISSUE TITLE
Unable to start activity ComponentInfo{com.github.dhaval2404.imagepicker.ImagePickerActivity

### ISSUE THREAD

**Issue by vinzaceto** [Dhaval2404/ImagePicker#18]
I received this error using this library:
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.dhaval2404.imagepicker.ImagePickerActivity}: kotlin.TypeCastException: null cannot be cast to non-null type com.github.dhaval2404.imagepicker.constant.ImageProvider
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2419)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2479)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5420)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by kotlin.TypeCastException: null cannot be cast to non-null type com.github.dhaval2404.imagepicker.constant.ImageProvider
       at com.github.dhaval2404.imagepicker.ImagePickerActivity.loadBundle(ImagePickerActivity.kt:49)
       at com.github.dhaval2404.imagepicker.ImagePickerActivity.onCreate(ImagePickerActivity.kt:38)
       at android.app.Activity.performCreate(Activity.java:6280)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2372)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2479)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5420)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

How can I resolve this issue?
Thanks

**Comment by Dhaval2404** [comment]
@vinzaceto Can you please help me with the steps to reproduce the issue. Thanks.

**Comment by Dhaval2404** [comment]
This issue has been closed because it has not had recent activity. Thank you for your contributions.
