### ISSUE TITLE
Crash app when scale bitmap

### ISSUE THREAD

**Issue by finnvna** [Dhaval2404/ImagePicker#248]
**Catch exception !!!**
`java.lang.RuntimeException: An error occured while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:304)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.IllegalArgumentException: width and height must be > 0
        at android.graphics.Bitmap.createBitmap(Bitmap.java:815)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:794)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:761)
        at com.github.dhaval2404.imagepicker.util.ImageUtil.decodeSampledBitmapFromFile(ImageUtil.kt:124)
        at com.github.dhaval2404.imagepicker.util.ImageUtil.compressImage(ImageUtil.kt:54)
        at com.github.dhaval2404.imagepicker.provider.CompressionProvider.applyCompression(CompressionProvider.kt:200)
        at com.github.dhaval2404.imagepicker.provider.CompressionProvider.startCompression(CompressionProvider.kt:140)
        at com.github.dhaval2404.imagepicker.provider.CompressionProvider.access$startCompression(CompressionProvider.kt:22)
        at com.github.dhaval2404.imagepicker.provider.CompressionProvider$startCompressionWorker$1.doInBackground(CompressionProvider.kt:113)
        at com.github.dhaval2404.imagepicker.provider.CompressionProvider$startCompressionWorker$1.doInBackground(CompressionProvider.kt:109)`

This is your code: com.github.dhaval2404.imagepicker.util.ImageUtil

        var scaledBitmap: Bitmap? = null
        try {
            scaledBitmap = Bitmap.createBitmap(actualWidth, actualHeight, Bitmap.Config.ARGB_8888)
        } catch (exception: OutOfMemoryError) {
            exception.printStackTrace()
        }

        val ratioX = actualWidth / options.outWidth.toFloat()
        val ratioY = actualHeight / options.outHeight.toFloat()
        val middleX = actualWidth / 2.0f
        val middleY = actualHeight / 2.0f

        val scaleMatrix = Matrix()
        scaleMatrix.setScale(ratioX, ratioY, middleX, middleY)

        val canvas = Canvas(scaledBitmap!!)
        canvas.setMatrix(scaleMatrix)
        canvas.drawBitmap(
            bmp!!, middleX - bmp.width / 2,
            middleY - bmp.height / 2, Paint(Paint.FILTER_BITMAP_FLAG)
        )
        bmp.recycle()

        val matrix = Matrix()
        scaledBitmap = Bitmap.createBitmap(
            scaledBitmap, 0, 0, scaledBitmap.width,
            scaledBitmap.height, matrix, true
        )

        return scaledBitmap

**Comment by yuv-red** [comment]
Any update on this? facing the same issue and numbers are getting increased... @Dhaval2404
