### ISSUE TITLE
crashing android app version 2.1

### ISSUE THREAD

**Issue by vishalkumarsinghvi** [Dhaval2404/ImagePicker#290]
Fatal Exception: android.view.InflateException: Binary XML file line #23: Binary XML file line #23: Error inflating class androidx.appcompat.widget.AppCompatImageView

Caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
       at android.view.LayoutInflater.createView(LayoutInflater.java:647)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
       at com.github.dhaval2404.imagepicker.util.DialogHelper.showChooseAppDialog(DialogHelper.java:21)
       at com.github.dhaval2404.imagepicker.ImagePicker$Builder.createIntent(ImagePicker.java:21)
       at com.streamkast.studio.ui.activitys.createEvent.CreateEventActivity.openImagePicker(CreateEventActivity.java:21)
       at com.streamkast.studio.ui.activitys.createEvent.CreateEventActivity.onCreate$lambda-4(CreateEventActivity.java:21)
       at com.streamkast.studio.ui.activitys.createEvent.CreateEventActivity$$InternalSyntheticLambda$0$4a8ad220d1c918bf4ec7e029bb97e8bf1f171745cd8cdbafd8837b294da20768$0.onClick$bridge(CreateEventActivity.java:21)
       at android.view.View.performClick(View.java:6294)
       at android.view.View$PerformClick.run(View.java:24770)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

I've tested it on android 8 and I'm using imagepicker:2.1

**Comment by kadyanmanjul** [comment]
Same ..
But mine i crashing at 
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.joshtalks.joshskills/com.yalantis.ucrop.UCropActivity}: android.view.InflateException: Binary XML file line #29 in com.joshtalks.joshskills:layout/ucrop_controls: Binary XML file line #49 in com.joshtalks.joshskills:layout/ucrop_layout_rotate_wheel: Error inflating class ImageView
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3839)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3997)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2380)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:257)
       at android.app.ActivityThread.main(ActivityThread.java:8335)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1032)

**Comment by vishalkumarsinghvi** [comment]
@Dhaval2404 Any update on this ?.
