### ISSUE TITLE
Crash when selecting camera

### ISSUE THREAD

**Issue by Semedaki** [Dhaval2404/ImagePicker#336]
Hello,
I have this problem, happening only in OnePlus8Pro devices, with android 11. The version of ImagePicker I use is 2.1.
When the user selects the camera option, the following crash happens:

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.project.name/com.github.dhaval2404.imagepicker.ImagePickerActivity}: java.lang.IllegalArgumentException: Failed to find configured root that contains /data/local/tmp/external/IMG_20231101_041618651.jpg
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3433)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3607)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2068)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7680)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:423)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by arvindkkore** [comment]
I have the same issue

**Comment by lolucosmin** [comment]
Same issue here:
Unable to start activity ComponentInfo{appyness.mhsc/com.github.dhaval2404.imagepicker.ImagePickerActivity}: java.lang.IllegalArgumentException: Failed to find configured root that contains /data/local/tmp/external/IMG_20240116_083529892.jpg

**Comment by mushtaq99** [comment]
same issue

**Comment by ZoobiApps** [comment]
same issue came in my OnePlus8Pro device android 11.

**Comment by thanhnhan111093** [comment]
same issue, firebase report on device OnePlus8Pro
Caused by java.lang.IllegalArgumentException: Failed to find configured root that contains /data/local/tmp/external/IMG_20241118_193906787.jpg
       at androidx.core.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:867)
       at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:467)
       at com.github.dhaval2404.imagepicker.util.IntentUtils.getCameraIntent(IntentUtils.kt:79)
       at com.github.dhaval2404.imagepicker.provider.CameraProvider.startCameraIntent(CameraProvider.kt:126)
       at com.github.dhaval2404.imagepicker.provider.CameraProvider.checkPermission(CameraProvider.kt:107)
       at com.github.dhaval2404.imagepicker.provider.CameraProvider.startIntent(CameraProvider.kt:96)
       at com.github.dhaval2404.imagepicker.ImagePickerActivity.loadBundle(ImagePickerActivity.kt:82)
       at com.github.dhaval2404.imagepicker.ImagePickerActivity.onCreate(ImagePickerActivity.kt:44)
       at android.app.Activity.performCreate(Activity.java:7994)
       at android.app.Activity.performCreate(Activity.java:7978)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1548)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3406)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3607)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2068)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7680)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:423)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by Seoras** [comment]
I'm trialing a fix, live on Play store, for this that changes the "authority" string used in utils/IntentUtils.kt
The call to 
`FileProvider.getUriForFile(context, authority, file)`
appears twice in that file and it is the cause, I think, of this crash for that brand/model of phone which seems to be more strict.
My fix is to use this string for authority.
`val authority = context.packageName + ".provider"`
So far so good.
The correct fix, if this is it, would be to change in strings.xml
`<string name="image_picker_provider_authority_suffix" translatable="false">.imagepicker.provider</string>`
to 
`<string name="image_picker_provider_authority_suffix" translatable="false">.provider</string>`
It also gets used in utils/IntentUtil.kt where I haven't tried changing it yet.
Anyone agree/disagree with this suggested fix?
