### ISSUE TITLE
Performing pause of activity that is not resumed

### ISSUE THREAD

**Issue by DipakSharmaAgile** [Dhaval2404/ImagePicker#48]
I'm using this library for tablet app. I'm opening the camera by your method and clicking on back button it throwing the exception. and unable to go back. 
`Performing pause of activity that is not resumed: {com.xxx/com.github.dhaval2404.imagepicker.ImagePickerActivity}
    java.lang.RuntimeException: Performing pause of activity that is not resumed: {com.xxx/com.github.dhaval2404.imagepicker.ImagePickerActivity}

**Comment by Dhaval2404** [comment]
@DipakSharmaAgile Can you please try once on the latest version(v1.6).

**Comment by DipakSharmaAgile** [comment]
Thanks, 
It is fixed now, so I'm closing this issue.

**Comment by Dhaval2404** [comment]
@DipakSharmaAgile Thank you so much for the feedback..!!

**Comment by DipakSharmaAgile** [comment]
I can go back to my screen when clicking on back button but. exception is still there and while perming this scenario in fragment it's getting crash and restarting the activity.

**Comment by Dhaval2404** [comment]
@DipakSharmaAgile Are you still getting **Performing pause of activity that is not resumed** exception?

**Comment by DipakSharmaAgile** [comment]
Yes. I'm still getting it in v1.6

**Comment by Dhaval2404** [comment]
@DipakSharmaAgile Can you please send me a video of the issue? This will help me to better understand the issue. I have checked this scenario in the various devices (including Nexus 9 Tablet - Android 7.1.1) and it seems working fine.

Thank you again for the response. Your response is helping me to improve this library.

**Comment by Dhaval2404** [comment]
@DipakSharmaAgile Can you please try this sample app: [Sample App v1.6]( https://github.com/Dhaval2404/ImagePicker/releases/download/v1.6/ImagePicker-v1.6.apk)

**Comment by DipakSharmaAgile** [comment]
Hello @Dhaval2404 ,
We cannot provide the video of our application and we tried your sample app in our tablet and it has exception too. let me share the device info and log here. 

`2020-01-08 09:54:36.489 12627-12627/com.github.dhaval2404.imagepicker.sample E/ActivityThread: Performing pause of activity that is not resumed: {com.github.dhaval2404.imagepicker.sample/com.github.dhaval2404.imagepicker.ImagePickerActivity}
    java.lang.RuntimeException: Performing pause of activity that is not resumed: {com.github.dhaval2404.imagepicker.sample/com.github.dhaval2404.imagepicker.ImagePickerActivity}
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4214)
        at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4179)
        at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:45)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1959)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7080)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
2020-01-08 09:54:36.490 12627-12627/com.github.dhaval2404.imagepicker.sample E/ActivityThread: Performing pause of activity that is not resumed: {com.github.dhaval2404.imagepicker.sample/com.github.dhaval2404.imagepicker.sample.MainActivity}
    java.lang.RuntimeException: Performing pause of activity that is not resumed: {com.github.dhaval2404.imagepicker.sample/com.github.dhaval2404.imagepicker.sample.MainActivity}
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4214)
        at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4179)
        at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:45)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1959)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7080)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)`

![device-2020-01-08-095117](https://user-images.githubusercontent.com/43946705/71950437-3ee67900-31fd-11ea-9847-e23bc34c6e59.png)

![image](https://user-images.githubusercontent.com/43946705/71950451-4f96ef00-31fd-11ea-8038-b1343f426508.png)

**Comment by Dhaval2404** [comment]
Thank you so much for the feedback @DipakSharmaAgile .

**Comment by DipakSharmaAgile** [comment]
@Dhaval2404 
We added one line in Manifest
`android:configChanges="orientation|keyboardHidden|screenSize"`

still exception is there but that is not causing any issue. so I'm closing this bug.
