### ISSUE TITLE
When I'm choosing camera, I'm getting crash below Android 8.0.0 Samsung S7

### ISSUE THREAD

**Issue by SergeyMilevskiy** [Dhaval2404/ImagePicker#53]
```
com.github.dhaval2404.imagepicker.ImagePickerActivity}: java.lang.IllegalArgumentException: Missing android.support.FILE_PROVIDER_PATHS meta-data
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
at android.app.ActivityThread.-wrap11(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6944)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) Caused by: java.lang.IllegalArgumentException: Missing android.support.FILE_PROVIDER_PATHS meta-data
at androidx.core.content.FileProvider.parsePathStrategy(FileProvider.java:613)
at androidx.core.content.FileProvider.getPathStrategy(FileProvider.java:579)
at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:417)
at com.github.dhaval2404.imagepicker.util.IntentUtils.getCameraIntent(IntentUtils.kt:75)
at com.github.dhaval2404.imagepicker.provider.CameraProvider.startCameraIntent(CameraProvider.kt:119)
at com.github.dhaval2404.imagepicker.provider.CameraProvider.checkPermission(CameraProvider.kt:100)
at com.github.dhaval2404.imagepicker.provider.CameraProvider.startIntent(CameraProvider.kt:89)
at com.github.dhaval2404.imagepicker.ImagePickerActivity.loadBundle(ImagePickerActivity.kt:104)
at com.github.dhaval2404.imagepicker.ImagePickerActivity.onCreate(ImagePickerActivity.kt:56)
at android.app.Activity.performCreate(Activity.java:7183)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)
```

**Comment by SergeyMilevskiy** [comment]
For those who faced the same problem =>
Before start lib
`val builder = StrictMode.VmPolicy.Builder()
        StrictMode.setVmPolicy(builder.build())`

**Comment by hixfield** [comment]
I think I have the same problem. I'm getting a "System UI has stopped".
To simulate:
- Run in simulator SDK 26
- install my app (using this lib) from scratch (so that no permission for camera has been received yet)
- I press button to select a new profile picture (that is when I use the lib in my app)
- The pop-up appears to select between camera - library pictures (so far so good)
- Press camera and then I briefly see the "Allow xxxx to access...." immediately overplayed by a "System UI has stopped" error message :

<img width="456" alt="image" src="https://user-images.githubusercontent.com/9302613/79599229-6e9efa00-80e5-11ea-956b-4eed8176d0b0.png">

- Pressing [close app] in this message, just pop-up the same "System UI has stopped" message over and over again...
- If I am fast enough and press the [Allow] button on the initial message (underneath the "System UI has stopped", then pressing [close app] successfully opens the camera app
- Once the app has camera approval then all works as expected

So I guess there is an issue when pressing camera and no permission has been given yet?

In my AndroidManifest.xml I have indeed a provider section like so:

        <provider
                android:name="com.facebook.FacebookContentProvider"
                android:authorities="@string/facebook_content_provider"
                android:exported="true" />

**Comment by hixfield** [comment]
Since the problem happend in the simulator I created a new simulator configuration with Android pixel 2 and SDK 26. Here the problem is gone. I also found a lot of references to "system UI has stopped" (e.g. on SOV https://stackoverflow.com/questions/15678520/android-emulator-error-system-ui-has-stopped). This leads me to believe its probably an bug in the simulator itself...
