### ISSUE TITLE
!!! FAILED BINDER TRANSACTION !!!  (parcel size = 1642552)

### ISSUE THREAD

**Issue by Kreateyou** [Dhaval2404/ImagePicker#89]
I am getting this error after selecting any image 
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.app.debug, PID: 22100
    java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1642552 bytes
        at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:161)
        at android.os.Handler.handleCallback(Handler.java:888)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8147)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
     Caused by: android.os.TransactionTooLargeException: data parcel size 1642552 bytes
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(BinderProxy.java:526)
        at android.app.IActivityTaskManager$Stub$Proxy.activityStopped(IActivityTaskManager.java:4561)
        at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:145)
        at android.os.Handler.handleCallback(Handler.java:888) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:213) 
        at android.app.ActivityThread.main(ActivityThread.java:8147) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101) 
```

**Comment by Dhaval2404** [comment]
@Kreateyou Can you please provide device info with android version?

**Comment by Kreateyou** [comment]
> @Kreateyou Can you please provide device info with android version?

Android Version:10
Device: Huawei p30 lite model: MAR-LX1m

**Comment by kibotu** [comment]
well parcel size is capped at 10MB (1642552 bytes), dunno what we parcel that could be so huge

**Comment by klaszlo8207** [comment]
I am getting the same, and crashes, what is the solution?
